"""
Alibaba Cloud GDB Graph Database Query Tool.
Query water treatment material knowledge graph.
"""
from gremlin_python.driver import client, serializer
from gremlin_python.driver.protocol import GremlinServerError
import json
from typing import List, Dict, Any, Optional
import os
from dotenv import load_dotenv

load_dotenv()


class GDBTool:
    """Alibaba Cloud GDB Graph Database Query Tool"""
    
    def __init__(self):
        """Initialize GDB connection"""
        self.host = os.getenv('GDB_HOST', '')
        self.port = int(os.getenv('GDB_PORT', '3734'))
        self.username = os.getenv('GDB_USERNAME', '')
        self.password = os.getenv('GDB_PASSWORD', '')
        self.graph = 'g'
        self._client = None
    
    def _get_client(self):
        """Get Gremlin client"""
        if self._client is None:
            url = f"ws://{self.host}:{self.port}/gremlin"
            self._client = client.Client(
                url,
                self.graph,
                username=self.username,
                password=self.password,
                message_serializer=serializer.GraphSONSerializersV3d0()
            )
        return self._client
    
    def query_catalyst_degradation(
        self,
        catalyst_name: str
    ) -> Dict[str, Any]:
        """
        Query pollutants that can be degraded by a catalyst.
        
        Args:
            catalyst_name: Catalyst name (e.g.: SO4, H2O2, TiO2)
            
        Returns:
            Dict containing pollutant list
        """
        try:
            c = self._get_client()
            
            query = f"""
                g.V().has('Catalyst', 'name', '{catalyst_name}')
                 .out('DEGRADES')
                 .values('name')
            """
            
            result = c.submit(query).all().result()
            pollutants = list(result) if result else []
            
            return {
                'success': True,
                'catalyst': catalyst_name,
                'pollutants': pollutants,
                'count': len(pollutants)
            }
            
        except GremlinServerError as e:
            return {
                'success': False,
                'error': f"GDB query error: {str(e)}",
                'catalyst': catalyst_name
            }
        except Exception as e:
            return {
                'success': False,
                'error': str(e),
                'catalyst': catalyst_name
            }
    
    def query_catalyst_active_species(
        self,
        catalyst_name: str
    ) -> Dict[str, Any]:
        """
        Query active species generated by a catalyst.
        
        Args:
            catalyst_name: Catalyst name
            
        Returns:
            Dict containing active species list
        """
        try:
            c = self._get_client()
            
            query = f"""
                g.V().has('Catalyst', 'name', '{catalyst_name}')
                 .out('GENERATES')
                 .values('name')
            """
            
            result = c.submit(query).all().result()
            species = list(result) if result else []
            
            return {
                'success': True,
                'catalyst': catalyst_name,
                'active_species': species,
                'count': len(species)
            }
            
        except Exception as e:
            return {
                'success': False,
                'error': str(e),
                'catalyst': catalyst_name
            }
    
    def query_pollutant_catalysts(
        self,
        pollutant_name: str
    ) -> Dict[str, Any]:
        """
        Query catalysts that can degrade a pollutant.
        
        Args:
            pollutant_name: Pollutant name (e.g.: CIP, BPA, Tetracycline)
            
        Returns:
            Dict containing catalyst list
        """
        try:
            c = self._get_client()
            
            query = f"""
                g.V().has('Pollutant', 'name', '{pollutant_name}')
                 .in('DEGRADES')
                 .values('name')
            """
            
            result = c.submit(query).all().result()
            catalysts = list(result) if result else []
            
            return {
                'success': True,
                'pollutant': pollutant_name,
                'catalysts': catalysts,
                'count': len(catalysts)
            }
            
        except Exception as e:
            return {
                'success': False,
                'error': str(e),
                'pollutant': pollutant_name
            }
    
    def query_catalyst_full_info(
        self,
        catalyst_name: str
    ) -> Dict[str, Any]:
        """
        Query complete catalyst info (degradable pollutants + generated active species).
        
        Args:
            catalyst_name: Catalyst name
            
        Returns:
            Dict containing complete information
        """
        try:
            degradation = self.query_catalyst_degradation(catalyst_name)
            species = self.query_catalyst_active_species(catalyst_name)
            
            if degradation['success'] and species['success']:
                return {
                    'success': True,
                    'catalyst': catalyst_name,
                    'degrades_pollutants': degradation['pollutants'],
                    'generates_species': species['active_species'],
                    'total_pollutants': degradation['count'],
                    'total_species': species['count']
                }
            else:
                return {
                    'success': False,
                    'error': 'Failed to query complete information',
                    'catalyst': catalyst_name
                }
                
        except Exception as e:
            return {
                'success': False,
                'error': str(e),
                'catalyst': catalyst_name
            }
    
    def get_all_pollutants(self) -> Dict[str, Any]:
        """Get all pollutants list"""
        try:
            c = self._get_client()
            query = "g.V().hasLabel('Pollutant').values('name')"
            result = c.submit(query).all().result()
            
            return {
                'success': True,
                'pollutants': list(result) if result else [],
                'count': len(result) if result else 0
            }
        except Exception as e:
            return {'success': False, 'error': str(e)}
    
    def get_all_active_species(self) -> Dict[str, Any]:
        """Get all active species list"""
        try:
            c = self._get_client()
            query = "g.V().hasLabel('ActiveSpecies').values('name')"
            result = c.submit(query).all().result()
            
            return {
                'success': True,
                'active_species': list(result) if result else [],
                'count': len(result) if result else 0
            }
        except Exception as e:
            return {'success': False, 'error': str(e)}
    
    def get_top_catalysts(self, top_k: int = 10) -> Dict[str, Any]:
        """Get catalysts with highest connectivity"""
        try:
            c = self._get_client()
            query = f"""
                g.V().hasLabel('Catalyst')
                 .project('name', 'degree')
                 .by('name')
                 .by(bothE().count())
                 .order().by(select('degree'), desc)
                 .limit({top_k})
            """
            result = c.submit(query).all().result()
            
            catalysts = []
            if result:
                for item in result:
                    catalysts.append({
                        'name': item['name'],
                        'connections': item['degree']
                    })
            
            return {
                'success': True,
                'top_catalysts': catalysts,
                'count': len(catalysts)
            }
        except Exception as e:
            return {'success': False, 'error': str(e)}
    
    def close(self):
        """Close client connection"""
        if self._client:
            self._client.close()
            self._client = None


# Create global instance
def get_gdb_tool() -> GDBTool:
    """Get GDB tool instance"""
    return GDBTool()
